name: master

on:
  push:
    branches:
      - master

jobs:
  wrapper:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Build library
        run: dotnet build src/WkHtmlTo.Wrapper/WkHtmlTo.Wrapper.csproj --configuration release
  aspnetcore-wrapper:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Build library
        run: dotnet build src/WkHtmlTo.Wrapper.AspNetCore/WkHtmlTo.Wrapper.AspNetCore.csproj --configuration release
  blazor_server-wrapper:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: | 
            8.0.x
      - name: Build library
        run: dotnet build src/WkHtmlTo.Wrapper.BlazorServer/WkHtmlTo.Wrapper.BlazorServer.csproj --configuration release
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and run .net core tests
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Test Mids
        run: |
          dotnet build tests/WkHtmlToPdf.Wrapper.Tests/WkHtmlToPdf.Wrapper.Tests.csproj
          dotnet test tests/WkHtmlToPdf.Wrapper.Tests/WkHtmlToPdf.Wrapper.Tests.csproj
  publish-wrapper:
    needs: [wrapper, test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet
        run: |
          dotnet build src/WkHtmlTo.Wrapper/WkHtmlTo.Wrapper.csproj --configuration release
          nuget push src/WkHtmlTo.Wrapper/bin/release/WkHtmlTo.Wrapper.1.0.0.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
  publish-aspnetcore-wrapper:
    needs: [aspnetcore-wrapper, test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet
        run: |
          dotnet build src/WkHtmlTo.Wrapper.AspNetCore/WkHtmlTo.Wrapper.AspNetCore.csproj --configuration release
          nuget push src/WkHtmlTo.Wrapper.AspNetCore/bin/release/WkHtmlTo.Wrapper.AspNetCore.1.0.0.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
  publish-blazor_server-wrapper:
    needs: [blazor_server-wrapper, test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet
        run: |
          dotnet build src/WkHtmlTo.Wrapper.BlazorServer/WkHtmlTo.Wrapper.BlazorServer.csproj --configuration release
          nuget push src/WkHtmlTo.Wrapper.BlazorServer/bin/release/WkHtmlTo.Wrapper.BlazorServer.1.0.0.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate